### ISSUE TITLE
Crash on CM12

### ISSUE THREAD

**Issue by andyboeh** [tobykurien/BatteryFu#18]
I'm a big fan of BatteryFu and have been using it very successfully on my Moto G 2014 on Stock ROM. Yesterday, I switched to CM12 and BatteryFu keeps crashing.

After startup (or after reboot) it only displays "Unfortunately, BatteryFu has stopped" and toggling does not seem to work. The notification remains in the status bar, though.

Any hints?

I can provide logcats later on.

edit: I didn't check the source, but it might be related to Google having removed the setEnableMobileDataMethod as discussed http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later

**Comment by tobykurien** [comment]
Thanks for the link @andyboeh - it does appear that KitKat is the end of the road for BatteryFu. I will try to add support for rooted Android 5 devices once I have a CM12 device myself.

**Comment by tobykurien** [comment]
I've tested the current master branch, and it seems to work stable on KitKat. Now testing on Lollipop (CyanogenMod 12), and it seems to work when granted root. Do you have a non-rooted Lollipop device to test it on?

**Comment by andyboeh** [comment]
Yes, my current "DataService" branch is very similar to your master branch and works fine on KitKat, too (CM11). Unfortunately, I need my device as a daily driver and can't install stock Lollipop right now.

**Comment by tobykurien** [comment]
Lollipop seems to be working (if granted root), so I'll make a release.
