### ISSUE TITLE
Build failure with gradle 1.8

### ISSUE THREAD

**Issue by RealRancor** [tobykurien/BatteryFu#22]
Hi,

when trying to build the app on f-droid with gradle 1.8 (forced by https://github.com/tobykurien/BatteryFu/blob/master/build.gradle#L12-L14) the build is failing with a message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/com.tobykurien.batteryfu/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'com.tobykurien.batteryfu'.
> Could not create plugin of type 'AppPlugin'.
```

Removing the mentioned line and building the app with gradle 2.2.1 worked without a problem.

**Comment by tobykurien** [comment]
Thanks for reporting, I didn't check the gradle build since I use Eclipse. Will fix.

**Comment by tobykurien** [comment]
Gradle build updated.
