### ISSUE TITLE
BatteryFu icon disappears after a while (v1.46)

### ISSUE THREAD

**Issue by tobykurien** [tobykurien/BatteryFu#23]
Not sure when or why, but icon disappears and you have to restart the app.

**Comment by andyboeh** [comment]
I can confirm this, I switched back to your version from F-Droid a few days back. Sometimes, the icon disappears immediately after clicking, e.g., on "Go Online Now" and re-appears a few seconds later.

Strangely enough, this does not happen with my fork (which has the settings class implemented a bit differently).

**Comment by dittaeva** [comment]
I can also confirm thism, using 1.46 from F-Droid.

**Comment by dittaeva** [comment]
I can also confirm this on SlimROM 4.4.4, using 1.46 from F-Droid.

> but icon disappears and you have to restart the app

From this it seems BateryFu is not running. In my case it is running, and the icon is visible on the lock screen, but when unlocked the icon is not there anymore (however the app is running).

**Comment by tobykurien** [comment]
Thanks for the feedback. Question is - does the icon automatically re-appear at the next sync cycle? I think this is just a simple case of the notification being cleared by mistake.

**Comment by dittaeva** [comment]
@tobykurien wrote:
>does the icon automatically re-appear at the next sync cycle?

In my case no. My sync cycle is every two hours, and I've been at work for 6 hours now, and only see the icon in the lock screen.

**Comment by andyboeh** [comment]
When it disappears because of an interaction, i.e. "Go Online Now", it re-appears after a few seconds. Occasionally, it doesn't and I have to start it from the App Draw.
I've never noticed it disappearing without any interaction at all.

**Comment by tobykurien** [comment]
@andyboeh could you test my current master branch? I may have figured out where the "icon disappearing" may be happening.

**Comment by andyboeh** [comment]
I just compiled and installed it - notification still running even after togglin "Go Online Now". Judging from the code, it looks good - my version has the line with nm.cancel() commented, so all makes perfect sense.

I'll test it for a day or two and let you know.

**Comment by tobykurien** [comment]
Awesome, seems good on my side too, so I'll make a release. Thanks.
