### ISSUE TITLE
Important suggestions.

### ISSUE THREAD

**Issue by joseliko7** [tobykurien/BatteryFu#31]
We must improve the design, translated into Spanish and add more options to save more battery.

**Comment by tobykurien** [comment]
Thanks to @dar5hak there will be spanish translations in the next release. Thanks for your suggestions.

**Comment by dar5hak** [comment]
@joseliko7 However, Spanish is not my first language, so if you find any errors that I might not have realized, please do make a pull request. The translations are at `res/values-es`.
