### ISSUE TITLE
Add setting to completely disable each SIM card (Flight mode) in Sleep time

### ISSUE THREAD

**Issue by ioctl-user** [tobykurien/BatteryFu#46]
It can be useful for travelers, that walking in area with bad mobile signal.
This function will save battery and allow receive SMS during Connect time.

**Comment by Siltaar** [comment]
See below.
(opened a new issue #50 for this previous content)

**Comment by Siltaar** [comment]
@ioctl-user The Auto Airplane Mode https://f-droid.org/en/packages/org.miamplayer.autoairplanemode/ app does exactly what you seek.

**Comment by ioctl-user** [comment]
> @ioctl-user The Auto Airplane Mode https://f-droid.org/en/packages/org.miamplayer.autoairplanemode/ app does exactly what you seek.

Thanks!
